  baseURL = "http://example.org/"
  languageCode = "en-us"
  title = "My New Hugo Site"

  [menu]
    [[menu.main]]
        name = "Notes"
        url = "/notes"
        weight = 20
    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 10
    [[menu.main]]
        name = "Now"
        url = "/now"
        weight = 40
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 30

