  baseURL = "http://oakst.io/"
  languageCode = "en-us"
  title = "Oak St. Electronics"

  [menu]
    [[menu.main]]
        name = "Notes"
        url = "/notes"
        weight = 20
    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 10
    [[menu.main]]
        name = "Now"
        url = "/now"
        weight = 40
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 30
    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 31

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4
