  baseURL = "http://example.org/"
  languageCode = "en-us"
  title = "My New Hugo Site"

  [menu]
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 30
    [[menu.main2]]
        name = "Notes"
        url = "/notes/"
        weight = 20
    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 10
